# 混合抽取流水线配置文件

# 基础配置
base:
  confidence_threshold: 0.7
  use_ner: true
  use_dedupe: true
  use_llm: true

# 切片配置
chunking:
  max_chunk_size: 2000
  overlap_size: 200
  chapter_priority: true

# LLM配置
llm:
  provider: "ollama"
  ollama_base_url: "http://10.20.124.89:11434"
  model: "deepseek-r1:32b"
  max_tokens: 1000
  temperature: 0.1
  timeout: 30

# 正则表达式模式 - 优化版本
patterns:
  project_name:
    - "项目名称[：:]\\s*([^，。\\n]{5,50})"
    - "工程名称[：:]\\s*([^，。\\n]{5,50})"
    - "([^，。\\n]{5,50}工程[^，。\\n]{0,50})"
  
  bidder:
    - "投标人[：:]\\s*([^，。\\n]{5,50})"
    - "投标单位[：:]\\s*([^，。\\n]{5,50})"
    - "投标公司[：:]\\s*([^，。\\n]{5,50})"
  
  bid_amount:
    - "投标总报价[：:]\\s*([^，。\\n]{5,30})"
    - "投标金额[：:]\\s*([^，。\\n]{5,30})"
    - "投标价[：:]\\s*([^，。\\n]{5,30})"
    - "愿意以人民币[（(]大写[)）]\\s*([^，。\\n]{5,50})[^，。\\n]*的投标总报价"
    - "投标总报价[^，。\\n]*人民币[（(]大写[)）]\\s*([^，。\\n]{5,50})"
    - "投标报价[：:]\\s*([^，。\\n]{5,30})"
    - "监测费[：:]\\s*([^，。\\n]{5,30})"
    - "\\|\\s*\\d+\\s*\\|\\s*监测费\\s*\\|\\s*([^，。\\n]{5,30})"
  
  deposit:
    - "保证金[：:]\\s*([^，。\\n]{5,30})"
    - "投标保证金[：:]\\s*([^，。\\n]{5,30})"
    - "履约保证金[：:]\\s*([^，。\\n]{5,30})"
  
  contact_info:
    - "联系电话[：:]\\s*([0-9\\-]{7,15})"
    - "手机[：:]\\s*([0-9\\-]{7,15})"
    - "电话[：:]\\s*([0-9\\-]{7,15})"
    - "传真[：:]\\s*([0-9\\-]{7,15})"
  
  date:
    - "([0-9]{4}[-/年][0-9]{1,2}[-/月][0-9]{1,2}[日]?)"
    - "([0-9]{4}年[0-9]{1,2}月[0-9]{1,2}日)"
  
  project_number:
    - "项目编号[：:]\\s*([A-Z0-9\\-]{5,20})"
    - "招标编号[：:]\\s*([A-Z0-9\\-]{5,20})"
    - "标书编号[：:]\\s*([A-Z0-9\\-]{5,20})"

# 同义词词典 - 用于Aho-Corasick匹配
synonyms:
  # 招标投标相关
  tender_keywords:
    - "招标"
    - "投标"
    - "中标"
    - "开标"
    - "评标"
    - "招标人"
    - "投标人"
    - "中标人"
    - "招标代理"
    - "招标文件"
    - "投标文件"
    - "招标公告"
    - "中标公告"
    - "招标控制价"
    - "投标报价"
    - "预算金额"
    - "项目金额"
    - "合同金额"
    - "投标保证金"
    - "履约保证金"
    - "质量保证金"
    - "投标有效期"
    - "投标截止时间"
    - "开标时间"
    - "评标时间"
    - "中标通知书"
    - "合同签订"
    - "项目编号"
    - "招标编号"
    - "合同编号"
    - "资格条件"
    - "资质要求"
    - "技术规范"
    - "商务条款"
    - "评标办法"
    - "评标标准"
    - "评标规则"
    - "评标程序"
    - "评标委员会"
    - "评标专家"
    - "评标结果"
    - "投标资格"
    - "投标人资格"
    - "联合体"
    - "联合投标"
    - "联合体协议"
    - "分包"
    - "转包"
    - "违法分包"
    - "围标"
    - "串标"
    - "废标"
    - "流标"
    - "重新招标"
    - "补充通知"
    - "澄清文件"
    - "答疑文件"
    - "变更通知"
    - "更正公告"
    - "中标候选人"
    - "中标公示"
    - "中标结果"
    - "合同条款"
    - "违约责任"
    - "争议解决"
    - "仲裁"
    - "诉讼"
    - "调解"
    - "验收标准"
    - "质量标准"
    - "工期要求"
    - "质量要求"
    - "安全要求"
    - "环保要求"
    - "技术参数"
    - "技术指标"
    - "性能指标"
    - "规格型号"
    - "品牌要求"
    - "产地要求"
    - "原产地"
    - "进口"
    - "国产"
    - "技术标准"
    - "行业标准"
    - "国家标准"
    - "国际标准"
    - "企业标准"
    - "技术方案"
    - "施工方案"
    - "组织方案"
    - "管理方案"
    - "质量保证"
    - "售后服务"
    - "质保期"
    - "保修期"
    - "维护保养"
    - "技术支持"
    - "培训服务"

  # 公司相关
  company_keywords:
    - "有限公司"
    - "股份有限公司"
    - "集团"
    - "公司"
    - "企业"
    - "有限责任公司"
    - "股份公司"
    - "合作社"
    - "事务所"
    - "研究院"
    - "设计院"
    - "工程公司"
    - "建设公司"
    - "开发公司"
    - "投资公司"
    - "咨询公司"
    - "监理公司"
    - "检测公司"
    - "评估公司"
    - "招标公司"

  # 职位相关
  position_keywords:
    - "总经理"
    - "董事长"
    - "法定代表人"
    - "项目经理"
    - "技术负责人"
    - "总工程师"
    - "副总工程师"
    - "技术总监"
    - "质量总监"
    - "安全总监"
    - "财务总监"
    - "人事总监"
    - "行政总监"
    - "运营总监"
    - "销售总监"
    - "市场总监"
    - "法务总监"
    - "审计总监"
    - "采购总监"
    - "物流总监"

  # 证书相关
  certificate_keywords:
    - "资质证书"
    - "营业执照"
    - "许可证"
    - "证书"
    - "资格证"
    - "等级证书"
    - "认证证书"
    - "检测报告"
    - "检验报告"
    - "测试报告"
    - "评估报告"
    - "审计报告"
    - "财务报告"
    - "年度报告"
    - "季度报告"
    - "月度报告"
    - "项目报告"
    - "技术报告"
    - "可行性报告"
    - "环境影响报告"

# 关键词词典
keywords:
  company:
    - "有限公司"
    - "股份有限公司"
    - "集团"
    - "公司"
    - "企业"
  
  position:
    - "总经理"
    - "董事长"
    - "法定代表人"
    - "项目经理"
    - "技术负责人"
  
  certificate:
    - "资质证书"
    - "营业执照"
    - "许可证"
    - "证书"
    - "资格证"

# 字段优先级
field_priorities:
  project_name: 1
  bidder: 2
  bid_amount: 3
  deposit: 4
  contact_info: 5
  date: 6
  project_number: 7

# 去重配置
dedupe:
  similarity_threshold: 0.8
  num_permutations: 128
  num_bands: 16

# 缓存配置
cache:
  enabled: true
  cache_dir: "./cache"
  expire_hours: 24 